# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stock-analyzer-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stockanalyzeracr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_694f5793a8564857b84482671f1c05e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b3d6ab5aadc046a8a0329186ea4671c0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stockanalyzeracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694f5793a8564857b84482671f1c05e0 }}/stock-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stock-analyzer-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bad9149187d246fd9a18c16c659e7126 }}
        images: 'stockanalyzeracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694f5793a8564857b84482671f1c05e0 }}/stock-frontend:${{ github.sha }}'